apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: flux-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-deploy
  template:
    metadata:
      labels:
        app: my-deploy
    spec:
      containers:
      - name: pod
        image: rajesh072/react-calculator
        ports:
        - containerPort: 3000
