apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: your-namespace
spec:
  replicas: 3  # Number of Nginx replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest  # Use the latest Nginx image
          ports:
            - containerPort: 80
