apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: flux-system
spec:
  selector:
    app: my-deploy
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
