apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: flux-system
spec:
  selector:
    app: nginx  # Select pods with the app=nginx label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort # Use ClusterIP for internal access, or NodePort/LoadBalancer for external access
